### PR TITLE
add options: cssFiles, scriptFiles

### PR DESCRIPTION
**Pull request by dexteryy**
For example:

```yml
# remarker.yml
dest: build
cssFiles:
  - 'styles/index.css'
scriptFiles:
  - 'node_modules/mermaid/dist/mermaid.min.js'
```

Output:

```
build
├── index.html
├── node_modules
│   └── mermaid
│       └── dist
│           └── mermaid.min.js
├── remark.js
└── styles
    └── index.css
```

```html
<!-- build/index.html -->
<!DOCTYPE html>
<html>
  <head>
    <title>....</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <link href="styles/index.css" rel="stylesheet" />
    <style type="text/css">
    <!-- ... -->
    <script src="remark.js"></script>
    <script src="node_modules/mermaid/dist/mermaid.min.js"></script>
    <script>
```

### CODE REVIEW

**Comment by kt3k** [comment]
Thanks for the contribution! 👍 

I like this change. Can you add some document to README as well?

**Comment by dexteryy** [comment]
@kt3k Done

**Comment by kt3k** [comment]
Thank you! Nice description 👍

**Comment by kt3k** [comment]
Published as v1.5.0.

**Pull request merged**
