### PR TITLE
fix cssFiles + scriptsFiles argv have to be array. add remark + remar…

### PR DESCRIPTION
**Pull request by wildcard**
fix cssFiles + scriptsFiles argv have to be array. 
add remark + remark emoji

now you can just run `remarker --cssFiles file.css` instead of `remarker --cssFiles file.css --cssFiles file.css`

and you can use `:apple:` to be converted to 🍎 emoji

### CODE REVIEW

**Comment by kt3k** [comment]
@wildcard 
Thanks for the contribution! `cssFiles` `scriptFiles` part of the change seems good to me.

The introduction of `gulp-remark` seems causing a problem. The examples don't seem working with this change. (You can test existing examples by the following steps:

```bash
cd examples/simple # or other example directory
node ../../index.js
```

This tool basically uses https://github.com/gnab/remark for parsing and constructing the slides (in browser). gulp-remark depends on https://github.com/remarkjs/remark, and this "remark" is totally different one and not compatible with gnab/remark.

If we process `:apple:` type emoji, I think we need to use more primitive tool like https://www.npmjs.com/package/node-emoji .

**Comment by kt3k** [comment]
I'd prefer you to revert emoji related part of the commit for the moment, and separate that change to anothor PR because other part seems no problem.

**Comment by wildcard** [comment]
@kt3k I've updated the PR. Please check if it is ok now :)

**Comment by wildcard** [comment]
Cool!

**Comment by kt3k** [comment]
Released as v1.9.1!

**Pull request merged**
